# Generated by Django 2.0.4 on 2020-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=400)),
                ('submitted_date', models.DateTimeField(auto_now_add=True, null=None)),
                ('issue_category', models.CharField(choices=[('IFC Issue', 'IFC Issue'), ('Billing Issue', 'Billing Issue'), ('Other', 'Other')], max_length=30)),
                ('issue_message', models.CharField(max_length=400)),
                ('reported_file', models.CharField(max_length=200)),
            ],
        ),
    ]
